/* Generated by scripts/generateServiceWorker.ts — do not edit. */
const CACHE_NAME = "jinkoujue-web-04dcf14da33c5616";
const PRECACHE_URLS = [
  "./_expo/static/js/web/index-5167ede767bd50b619600a8bc4bde9ee.js",
  "./_expo/static/js/web/index-a047b6e7ef73cfc184331836fad6249e.js",
  "./favicon.ico",
  "./index.html",
  "./manifest.json",
  "./metadata.json",
  "./privacy.html",
  "./pwa-icon.png",
  "./pwa-maskable.png"
];

self.addEventListener('install', (event) => {
  // skipWaiting 不可省：沒有它，新版 worker 會一直停在 waiting，
  // 要等舊版的每一個分頁都關掉才啟用 —— 裝到主畫面的 PWA 幾乎不會發生。
  // 2026-08-31 實測過缺這一行的後果：連續重載仍取舊 bundle，舊快取也不會被清。
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(names.filter((name) => name.startsWith('jinkoujue-web-') && name !== CACHE_NAME).map((name) => caches.delete(name))),
    ).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;
      if (event.request.mode === 'navigate') return caches.match('./index.html');
      return fetch(event.request);
    }),
  );
});
