/* Generated by scripts/generateServiceWorker.ts — do not edit. */
const CACHE_NAME = "jinkoujue-web-4c3cd0bf8cef7664";
const PRECACHE_URLS = [
  "./_expo/static/js/web/index-681691fb87fda164d72f139cf0d6eced.js",
  "./_expo/static/js/web/index-d994fa274ec7fb5f94c17745a1b861af.js",
  "./favicon.ico",
  "./index.html",
  "./manifest.json",
  "./metadata.json",
  "./pwa-icon.png",
  "./pwa-maskable.png"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(names.filter((name) => name.startsWith('jinkoujue-web-') && name !== CACHE_NAME).map((name) => caches.delete(name))),
    ).then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;
      if (event.request.mode === 'navigate') return caches.match('./index.html');
      return fetch(event.request);
    }),
  );
});
